data:
    name: homographies
    data_dir: output/custom_dataset
    image_dir: images
    image_list: custom_image_list.txt

    train_size: 300
    val_size: 44

    batch_size: 8
    num_workers: 8

    homography:
        difficulty: 0.7
        max_angle: 45
        patch_shape: [512, 208]

    photometric:
        name: lg

model:
    name: two_view_pipeline

    extractor:
        name: extractors.superpoint_open

        max_num_keypoints: 512
        force_num_keypoints: True

        detection_threshold: -1
        nms_radius: 4

        trainable: False

    ground_truth:
        name: matchers.homography_matcher

        th_positive: 3
        th_negative: 3

    matcher:
        name: matchers.lightglue

        filter_threshold: 0.1
        flash: false
        checkpointed: true

train:
    seed: 0

    epochs: 100

    optimizer: adam

    lr: 1e-4

    log_every_iter: 10
    eval_every_iter: 100

    save_every_iter: 1000

    lr_schedule:
        type: exp
        start: 20
        on_epoch: true
        exp_div_10: 10

    plot:
      - 5
      - gluefactory.visualization.visualize_batch.make_match_figures

benchmarks:
    hpatches:
        eval:
            estimator: opencv
            ransac_th: 0.5