data:
    name: homographies

    data_dir: /home/thippe/workspaces/AiMl/glue-factory/data/output/dataset
    image_dir: images
    image_list: null   # IMPORTANT: auto-use folder images

    train_size: 300
    val_size: 44

    batch_size: 4
    num_workers: 14

    homography:
        difficulty: 0.7
        max_angle: 45
        patch_shape: [512, 208]

    photometric:
        name: lg

model:
    name: two_view_pipeline

    extractor:
        name: extractors.aliked   # BEST for your setup

        max_num_keypoints: 512
        detection_threshold: 0.0

        trainable: false

    detector:
        name: null

    descriptor:
        name: null

    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3

    matcher:
        name: matchers.lightglue

        filter_threshold: 0.1
        flash: false
        checkpointed: true
        input_dim: 128

train:
    seed: 0
    epochs: 300

    optimizer: adam
    lr: 1e-4

    log_every_iter: 50
    eval_every_iter: 200

    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10

    plot:
        - 5
        - gluefactory.visualization.visualize_batch.make_match_figures

benchmarks:
    hpatches:
        eval:
            estimator: opencv
            ransac_th: 0.5
