data:
    name: homographies
    data_dir: output/dataset
    image_dir: images
    image_list: custom_image_list.txt
    train_size: 300
    val_size: 44
    batch_size: 4
    num_workers: 4
    homography:
        difficulty: 0.7
        max_angle: 45
        patch_shape: [512, 208]
    photometric:
        name: lg
    load_features:
        do: True
        path: "output/dataset/exports/custom_SP-k2048-nms4.h5"
        collate: False
        max_num_keypoints: 512
        force_num_keypoints: True
model:
    name: two_view_pipeline
    extractor:
        name: null
    allow_no_extract: True
    ground_truth:
        name: matchers.homography_matcher
        th_positive: 3
        th_negative: 3
    matcher:
        name: gluefactory_nonfree.superglue
        weights: outdoor
        filter_threshold: 0.2
train:
    seed: 0
    epochs: 100
    log_every_iter: 1
    eval_every_iter: 10
    lr: 1e-4
    lr_schedule:
        start: 20
        type: exp
        on_epoch: true
        exp_div_10: 10
    plot: [1, 'gluefactory.visualization.visualize_batch.make_match_figures']
